### ISSUE TITLE
F-Droid release

### ISSUE THREAD

**Issue by riverside6** [gematik/E-Rezept-App-Android#1]
Please consider to release this app also on F-Droid.
For not excluding degoogled Android users who either do not have, or (for privacy/trust etc. reasons) don't want to have access to the play store.
Thanks a lot for choosing the way to open source this app.

**Comment by fnordlicht** [comment]
Thank you for the suggestion. We are considering to release also on F-Droid, but we still need to address some issues beforehand. Watch this issue for updates on this topic.

**Comment by fnordlicht** [comment]
Instead of releasing on F-Droid or other stores besides Google Play and Huawei AppGallery, we decided to publish the APK for each released version here on Gihub starting with the [1.2.1 release](https://github.com/gematik/E-Rezept-App-Android/releases/tag/1.2.1). We think this is a good solution.

**Comment by riverside6** [comment]
That's very unfortunate. So all the users who don't have Google Play or Huawei AppGallery installed, have to check the GitHub page every now and then or even regularly?
Or will there be a feature, those users get notified when there's a new version available?
This is neihter a policy to provide this android app comfortably to everyone who runs android, nor is it a save way to ensure everyone uses the latest release with all fixes, compatibilities, etc.
This seems to be only a "good solution" for users who have GooglePlay or Huawei AppGallery installed on their phones.
What were the considerations that lead to this decision?

**Comment by Miademora** [comment]
You can get notified via github when a new release comes out. But i would assume you already know that.
My phone has 153 apps. I cant even imagine updating them all by hand, especially on security conscious apps.

**Comment by MaxGitHubAccount** [comment]
I think it's a pity that there should only be apk builds via Github. The aspect that I don't want to download and update all the apps individually, especially for an app that deals with health data and therefore very sensitive data, has already been mentioned. Furthermore, in contrast to F-Droid, this method does not offer reproducible builds. This further limits trust, as it is not clear whether other things are included in addition to the source code, so it loses the great advantage of open source.

**Comment by KasimiraEike** [comment]
> Instead of releasing on F-Droid or other stores besides Google Play and Huawei AppGallery, we decided to publish the APK for each released version here on Gihub starting with the [1.2.1 release](https://github.com/gematik/E-Rezept-App-Android/releases/tag/1.2.1). We think this is a good solution.

This is a great first step but a release on F-Droid would be awesome anyways.
It doesn't have to be done this year. Next year would be fine too.
F-Droid adds a layer of trust and makes updating a bit easier.

Thank you very much! 👍

**Comment by xandro0777** [comment]
Having the App in F-Droid would substantially raise its trustworthiness, just like it did for the Corona Encounter tracing App. Downloading Apps from Github is not safe.

**Comment by xandro0777** [comment]
FYI, a request for packaging this App has been entered into F-Droid.org tracker some time ago - https://gitlab.com/fdroid/rfp/-/issues/2586

While the project owner decided to not actively help with this afaics they don't appear to oppose it either, so anyone is free to help with some work on the above mentioned ticket and it will be packaged. If nothing else give it some thumbs up in the F-Droid tracker.

**Comment by licaon-kter** [comment]
there's a lot to fix: https://gitlab.com/fdroid/rfp/-/issues/2586#note_1791400091

this would need to be opt-in: https://github.com/gematik/E-Rezept-App-Android/issues/21

this changed: https://github.com/gematik/E-Rezept-App-Android/issues/13

also this was scary: https://github.com/gematik/E-Rezept-App-Android/issues/26

etc

**Comment by mabasger** [comment]
Dear all,
I would like to reopen this issue, as it is obviously of enough interest. From gematik side, we will prepare the CI to be capable to publish to F-Droid and the corresponding processes (Access Keys, legal stuff including the integrity-API issue, etc). The change from ML-Kit and Google Maps to something else will require some development effort. We lack here immediate available ressources, so it will take some time. I know that this is a bit frustrating (it´s so for us, too). But we can offer the acceptance of Pull Requests - so feel free to accelerate the change....
