### ISSUE TITLE
1.12.0 GitHub release missing

### ISSUE THREAD

**Issue by felschr** [gematik/E-Rezept-App-Android#10]
There's no 1.12.0 release on GitHub while this version has been available on Google Play for a while already.

**Comment by fnordlicht** [comment]
Hi @felschr,

version [1.12.1](https://github.com/gematik/E-Rezept-App-Android/releases/tag/1.12.1) was just released. Let us know what you think :)

**Comment by felschr** [comment]
The new version 1.12.2 & 1.13.1 haven't gotten any releases on GitHub again.
It would be really nice the releases could be kept in sync.
