### ISSUE TITLE
Couple findings in English texts

### ISSUE THREAD

**Issue by cygairko** [gematik/E-Rezept-App-Android#15]
1. Page title and navigation link for Orders page is written lowercase "orders"
2. lowercase "courier service" on Pharmacies page
3. Settings entries are mixing title case ("**P**rivacy **P**olicy") vs all lowercase ("**d**evice **s**ecurity") vs first upercase ("**O**rder new card")
4. Order page has German text for link "Verbinden"

**Comment by fnordlicht** [comment]
Hi @cygairko,
thank you very much for filing this issue. We'll look into it and post updates here. Stay tuned!

**Comment by luiseque** [comment]
Thanks, should be fixed latest within the next two releases :)
