### ISSUE TITLE
1.12.2, 1.13.1, 1.14.0 GitHub releases missing

### ISSUE THREAD

**Issue by felschr** [gematik/E-Rezept-App-Android#16]
As mentioned in #10, the new versions 1.12.2, 1.13.1, 1.14.0 haven't gotten any releases on GitHub again.
It would be really nice the releases could be kept in sync.

**Comment by fnordlicht** [comment]
Hi @felschr,

thank you very much for filing this issue. You're perfectly right, there were some releases missed during the vacation season and we're sorry for that.
But good news: There is a release for 1.14.0  available, unfortunately it has some issues when building. But you can work around this by taking a look at #17 and follow the hints there. We're sorry for this and will address this asap.
