### ISSUE TITLE
Gradle Build fails

### ISSUE THREAD

**Issue by crowmatix** [gematik/E-Rezept-App-Android#17]
Hallo,

ich wollte wie in der Readme beschrieben mit dem Befehl `gradle :android:assembleGooglePuExternalDebug -Pbuildkonfig.flavor=googlePuExternal` die .apk erzeugen und bekomme dann ein Build failed with exception: 
`task 'assembleGooglePuExternalDebug' not found in project ':android'`

![grafik](https://github.com/gematik/E-Rezept-App-Android/assets/91941203/1a2af57e-3313-4af0-9996-48c367cae69e)

Falls ich probiere auf `gradle :android:assembleGoogleTuInternalDebug -Pbuildkonfig.flavor=googleTuInternal` zu wechseln bekomme ich wieder ein Build failed with exception: `Task '.flavor=googleTuInternal' not found in root project 'E-Rezept' and its subprojects.`

![grafik](https://github.com/gematik/E-Rezept-App-Android/assets/91941203/d70f4235-2f0d-4b4a-85e2-9de8279c6525)

**Comment by fnordlicht** [comment]
Hi @crowmatix,

thank you very much for filing this issue. Actually, the variant 'ExternalDebug' isn't possible. 
If you use `gradle :android:assembleGooglePuExternalDebug -Pbuildkonfig.flavor=googlePuExternal` for a release build or `gradle :android:assembleGooglePuInternalDebug -Pbuildkonfig.flavor=googlePuInternal` it will succeed.
Unfortunately, there are other issues besides this one here that prevent a successful build with this release 1.14.0. To work around this, change line 9 in `gradle.properties` to `org.gradle.jvmargs=-Xmx4g -Dkotlin.daemon.jvm.options=-Xmx4g -XX:+UseParallelGC` and disable `ktlint` in line 34 of `.../android/build.gradle`. We will fix this in one of the upcoming releases.
