### ISSUE TITLE
Release newest build

### ISSUE THREAD

**Issue by TheBiostarfly** [gematik/E-Rezept-App-Android#18]
Please release the newest version of this app through github. 

And please considered improving the workflow through github so the release in the google play store and here are up-to-date.  As you can see in issue #10 it is not the first time this  happened

**Comment by TillPlewe** [comment]
Hello @TheBiostarfly ,
the latest versions have just been released.
Have a nice day :)

Hi @heapifyman ,
we are currently looking into replacing some of the Google dependencies in the app with other solutions. If they perform similarly, we will switch to them. Stay tuned for upcoming changes later this year.
Have a nice day :)

**Comment by TheBiostarfly** [comment]
Thank you!
