### ISSUE TITLE
Freigabe e-rezept-App auf weiterem Smartphone

### ISSUE THREAD

**Issue by fakerli** [gematik/E-Rezept-App-Android#19]
Angemeldet auf dem iphone mit erezept + epa-App.

Bei Anmeldung auf dem Androidphone muss ich die Anmeldung auf dem Iphone in der ePA-App freigeben.

Ist dies erfolgt, werde ich auf dem Android-Phone auf eine Website von das-e-rezept-fuer-deutschland.de/extauth?code=... weitergeleitet. Dieses endet auf einer 404-Page und eine Anmeldung ist somit nicht möglich.

**Comment by fakerli** [comment]
@Gematik-Entwicklung

**Comment by mfiebig** [comment]
Hallo @fakerli ,

 es tut uns dass die Anmeldung nicht funktioniert hat. Leider liegt der Teil des Prozesses nicht in unserer Hand. Bei Problemen mit dem Rücksprung in die E-Rezept-App wenden sie sich an die Krankenkasse. Sie können sich alternativ mit der elektronischen Gesundheitskarte (eGK) und der dazugehörigen PIN anmelden, die sie ggf. bei Ihrer Krankenkasse beantragen können.

**Comment by fakerli** [comment]
Für die Nachwelt: 

Was bei mir geholfen hat: In den App-Einstellungen (Android) das standardmäßige Öffnen der Links deaktivieren und wieder aktivieren. Obwohl das Öffnen der Links erlaubt war, funktionierte es erst nach einem Abwählen und wieder Anwählen.

![image](https://github.com/gematik/E-Rezept-App-Android/assets/12958497/15f410a2-dd66-470b-832d-a405d8e3a0c3)

![image](https://github.com/gematik/E-Rezept-App-Android/assets/12958497/ac2f2555-9ed0-497c-afe6-2037047389f8)

**Comment by dineshvg** [comment]
Hey @fakerli, eine Frage dazu.
Haben Sie zuvor in der App "Speicher löschen" durchgeführt? 

Wäre es außerdem möglich, uns mitzuteilen, bei welcher Version der App das Problem aufgetreten ist und vielleicht auch bei dem verwendeten Handy?

**Comment by dineshvg** [comment]
Closing issue since user has found a way to resolve it.
