### ISSUE TITLE
Current Release fails to install

### ISSUE THREAD

**Issue by Delegator9176** [gematik/E-Rezept-App-Android#20]
Hi the current apk-file from github is not installable.

When I download the apk and try to install it, the process starts and than aborts within a second.

If you guide me, I am able to provide some logs.

In addition I tried to install the app from the playstore and that works.

Maybe solving #18 also helps.

Thanks in advance

**Comment by TillPlewe** [comment]
Hello @Delegator9176 ,
the latest versions have just been released. Hopefully you can now install the latest apk from github. If you are still encountering any issues, please let us know. We will try to help you.
Have a nice day :)

**Comment by dineshvg** [comment]
Closing issue since latest APK is available
