### ISSUE TITLE
UX: Privacy consent button almost invisible

### ISSUE THREAD

**Issue by jottr** [gematik/E-Rezept-App-Android#23]
Just the first contact with the app must be an exercise in frustration for anyone with low contrast eyesight.
You know, older people for example.

<img width="886" alt="image" src="https://github.com/gematik/E-Rezept-App-Android/assets/2744198/4ab875fc-f593-4585-9017-e41a1e6e5891">

If they don't understand that they need to flip the switch, they won't be able to use this app.

Full context:
![Screenshot_1706142037](https://github.com/gematik/E-Rezept-App-Android/assets/2744198/3fde1112-8ede-4a09-a191-bbbec462b5ce)

Similar issue in light mode. 

<img width="813" alt="image" src="https://github.com/gematik/E-Rezept-App-Android/assets/2744198/2cbe4c51-fb60-41cf-baa3-a1c13d667e01">
 
<br />
<br />

 How did this pass QA until `v1.19.1`?!  

Screenshots were taken on an Android AVD. 
This is even worse on an actual Pixel 6 device.

I strongly recommend you read the Material UX Guidelines, especially the section on [Accessibility](https://m2.material.io/design/usability/accessibility.html#color-and-contrast).   
Even better, hire a capable UX designer that catches basic mistakes like these.

Oh, while you're rebuilding - you might want to sanity check your translations. You're mixing languages.

![Screenshot_1706142097](https://github.com/gematik/E-Rezept-App-Android/assets/2744198/d7e8f259-34c5-4439-b2b1-908575b83242)

**Comment by dineshvg** [comment]
Thanks for reporting @jottr . We are asking our UI/UX people to change it.

**Comment by dineshvg** [comment]
This is fixed in the release 1.20.0
