### ISSUE TITLE
Error when i run the app

### ISSUE THREAD

**Issue by ilovemyfamilyforever** [gematik/E-Rezept-App-Android#25]
i got this error:
`C:\Users\jcai\StudioProjects\E-Rezept-App-Android\app\features\build\generated\source\buildConfig\debug\de\gematik\ti\erp\app\features\BuildConfig.java:31: error: ';' expected
  public static final String orggradlejvmargs = "-Xmx4g -Dkotlin.daemon.jvm.options="-Xmx4g" -XX:+UseParallelGC";
`
```[tasklist]
### Tasks
- [ ] Fix app to build from github
```

**Comment by dineshvg** [comment]
We will make some fixes that we are able to build it from github without the required keys.

**Comment by tjpO** [comment]
Please checkout the newest version of release 1.26.0. The app should be buildable and executable again. If you encounter any issues, please let us know.
