### ISSUE TITLE
APK in GitHub release 1.20.0 has a different signature

### ISSUE THREAD

**Issue by felschr** [gematik/E-Rezept-App-Android#26]
The APK in the assets of the [1.20.0](https://github.com/gematik/E-Rezept-App-Android/releases/tag/1.20.0) release has a different signature than the previous releases (e.g. [1.19.1](https://github.com/gematik/E-Rezept-App-Android/releases/tag/1.19.1)).

This can be validated with different tools including [apksigner](https://developer.android.com/tools/apksigner) & [AppVerifier](https://github.com/soupslurpr/AppVerifier).

---

Via AppVerifier I see these signatures:

1.19.1:
```
de.gematik.ti.erp.app
B4:63:DF:B0:59:76:99:64:DD:74:97:21:48:0E:20:5A:52:D8:F0:F2:40:08:47:A9:E2:31:C3:55:8C:A2:D8:48
```

1.20.0:
```
de.gematik.ti.erp.app
76:D9:7E:A0:62:E7:25:F8:36:0B:E2:42:3D:D7:63:88:BD:E6:54:BF:B6:A8:CE:72:D2:0E:D3:40:9B:CC:72:A5
```

**Comment by tjpO** [comment]
Hi @felschr, the 1.20.0 apk is now updated.
