### ISSUE TITLE
1.22.1, 1.23.0, 1.24.0, 1.25.0 and 1.25.1 Github releases missing

### ISSUE THREAD

**Issue by snoo0py** [gematik/E-Rezept-App-Android#31]
As mentinoed in #10 and #16 the last versions of this year are missing. It would be great to get the updated code and missing releases on github.
Is there another problem besides vacation, as [mentioned](https://github.com/gematik/E-Rezept-App-Android/issues/16#issuecomment-1719584823) by @fnordlicht, that delays the sync?

**Comment by cweiske** [comment]
I cannot access a current prescription my doctor gave me because of a bug in the current public version.
Support told me to install a newer version (1.25) which I can't because the source code is missing, and I am using a google-free Android distribution.

**Comment by cweiske** [comment]
They plan to fix their build pipeline within the next 2 weeks: https://x.com/gematik1/status/1859626825153982713

**Comment by tjpO** [comment]
Hello @snoo0py & @cweiske,

the maintenance of the GitHub publishing infrastructure has been completed and
the latest version 1.26.0 has just been released. 

Hopefully you can now install the latest apk from github. 
If you are still encountering any issues, please let us know. 
We will try to help you.

There is currently no plan to release the missing versions.

Have a nice day and a happy holiday season :)

**Comment by cweiske** [comment]
Thank you for the release just before christmas!

I'll wait until it lands on F-Droid.
