### ISSUE TITLE
Missing sane default values for development builds

### ISSUE THREAD

**Issue by Adelrisk** [gematik/E-Rezept-App-Android#35]
## Behaviour:

The android app will crash on start given an incomplete configuration:

```
12-02 10:31:21.760 31744 31744 E AndroidRuntime: FATAL EXCEPTION: main
12-02 10:31:21.760 31744 31744 E AndroidRuntime: Process: de.gematik.ti.erp.app.test, PID: 31744
12-02 10:31:21.760 31744 31744 E AndroidRuntime: java.util.NoSuchElementException: Char sequence is empty.
12-02 10:31:21.760 31744 31744 E AndroidRuntime: 	at kotlin.text.StringsKt___StringsKt.last(_Strings.kt:180)
12-02 10:31:21.760 31744 31744 E AndroidRuntime: 	at de.gematik.ti.erp.app.di.EndpointHelper.getUriForEndpoint(EndpointHelper.kt:62)
12-02 10:31:21.760 31744 31744 E AndroidRuntime: 	at de.gematik.ti.erp.app.di.EndpointHelper.getIdpServiceUri(EndpointHelper.kt:49)
12-02 10:31:21.760 31744 31744 E AndroidRuntime: 	at de.gematik.ti.erp.app.di.NetworkModuleKt$networkModule$1$10.invoke(NetworkModule.kt:193)
12-02 10:31:21.760 31744 31744 E AndroidRuntime: 	at de.gematik.ti.erp.app.di.NetworkModuleKt$networkModule$1$10.invoke(NetworkModule.kt:177)
12-02 10:31:21.760 31744 31744 E AndroidRuntime: 	at org.kodein.di.bindings.Singleton$getFactory$1$1$1.invoke(standardBindings.kt:177)
12-02 10:31:21.760 31744 31744 E AndroidRuntime: 	at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
12-02 10:31:21.760 31744 31744 E AndroidRuntime: 	at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:177)
```

This happens when running the app with a relatively empty `ci-overrides.properties` file.

## Analysis

Apparently, the class `EndpointHelper` attempts to correct URLs by appending a trailing slash:

https://github.com/gematik/E-Rezept-App-Android/blob/master/app/features/src/debug/kotlin/de/gematik/ti/erp/app/di/EndpointHelper.kt#L62

```kotlin
        if (url.last() != '/') {
            url += '/'
        }
```

This code requires non-empty strings.

However, the config values used originate from the generated class `BuildKonfig`. The tooling generates a class like this:

```kotlin
public actual object BuildKonfig {
  /* SNIP */
  public actual val BASE_SERVICE_URI: String = ""

  public actual val IDP_SERVICE_URI: String = ""

  public actual val ERP_API_KEY: String = ""

  public actual val PHARMACY_SERVICE_URI: String = ""
``` 

## Expectations

I would not expect the app to crash on start after a clean clone of the repo and building the app.

I believe a combination of the following would help:

1. Provide a baseline for the `ci-overrides.properties` that contains meaningful defaults, either in the README or as a separate file (such as an additional `ci-overrides.example.properties`)
2. A description of the configurable values supported in `ci-overrides.properties`
3. Support for empty strings if these configuration values are actually optional. Beginning with this change `EndpointHelper`:

    ```diff
        private fun getUriForEndpoint(uri: EndpointUri): String {
            var url = uri.original
            if (isUriOverridden(uri)) {
                url = networkPrefs.getString(
                    uri.preferenceKey,
                    uri.original
                )!!
            }
    -       if (url.last() != '/') {
    +       if (url.isNotEmpty() && url.last() != '/') {
                url += '/'
            }
            return url
        }
    ```

**Comment by tjpO** [comment]
Please checkout the newest version of release 1.26.0 and the updated guidelines in the README.md. The app should be buildable and executable again. If you encounter any issues, please let us know.
