### ISSUE TITLE
Automatic builds & publication via releases

### ISSUE THREAD

**Issue by Myzel394** [gematik/E-Rezept-App-Android#4]
It would be nice to automatically creates builds (for example via [GitHub Actions](https://github.com/features/actions)) and publish them via [releases](https://github.com/gematik/E-Rezept-App-Android/releases).

**Comment by fnordlicht** [comment]
Hi @Myzel394, thank you for your suggestion. Starting with the [1.2.1](https://github.com/gematik/E-Rezept-App-Android/releases/tag/1.2.1) release, we will also publish the corresponding APK here on Github. Let us know if you have further suggestions.
