### ISSUE TITLE
Improve developer instructions

### ISSUE THREAD

**Issue by friedger** [gematik/E-Rezept-App-Android#7]
Running `gradle :android:assembleGooglePuExternalDebug -Pbuildkonfig.flavor=googlePuExternal` fails
* due to missing file ci-overrides.properties
* due to missing values for MAPS_API_KEY
* due to missing values for PHARMACY_SERVICE_URI_PU

**Comment by fnordlicht** [comment]
Hi Friedger,

thank you very much for filing this issue. We'll look into it and address it in the next release. Until then, this issue will remain open.

**Comment by fnordlicht** [comment]
This issue was addressed in [Release 1.8.0](https://github.com/gematik/E-Rezept-App-Android/releases/tag/1.8.0). If you have further findings, don't hesitate to open a new PR. Thanks for contributing!
