### ISSUE TITLE
Alternative Zuweisung v1.11.0-RC1

### ISSUE THREAD

**Issue by timorosenblatt** [gematik/E-Rezept-App-Android#9]
Hallo,
ich habe die neue Version 1.11.0-RC1-konnektathon-RU installiert,
im Debug - Menü "RedeemWithoutTI" aktiviert,
ein Token gescannt und versucht der Arcaden ApothekeTEST-ONLY zuzuweisen.

Direkt beim Zuweisen beendet sich die Anwendung.
Aktuell habe ich keinen Zugriff auf die Logs des Endpoints um zu kontrollieren, ob dort etwas angekommen ist.

Müsste die Zuweisung schon funktionieren?

**Comment by fnordlicht** [comment]
Hi @timorosenblatt,

thank you for opening this issue.

Let's discuss this in the upcoming Konnektathon since the general public has no clue what we're talking about here 😄 
Also feel free to contact us on Teams.
